// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package bookingDB

import (
	"context"

	"github.com/google/uuid"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (user_id, ticket_id, status)
VALUES ($1, $2, $3)
    RETURNING id, user_id, ticket_id, status, created_at
`

type CreateBookingParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TicketID int32     `json:"ticket_id"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking, arg.UserID, arg.TicketID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TicketID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
