# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pricing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpricing.proto\x12\x07pricing\"E\n\x0cPriceRequest\x12\x0f\n\x07seat_id\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x12\n\nbase_price\x18\x03 \x01(\x02\"8\n\rPriceResponse\x12\x13\n\x0b\x66inal_price\x18\x01 \x01(\x05\x12\x12\n\nmultiplier\x18\x02 \x01(\x02\x32K\n\x0ePricingService\x12\x39\n\x08GetPrice\x12\x15.pricing.PriceRequest\x1a\x16.pricing.PriceResponseBGZEgithub.com/dwikikusuma/ticket-rush/common/gen/go/pricing/v1;pricingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pricing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZEgithub.com/dwikikusuma/ticket-rush/common/gen/go/pricing/v1;pricingv1'
  _globals['_PRICEREQUEST']._serialized_start=26
  _globals['_PRICEREQUEST']._serialized_end=95
  _globals['_PRICERESPONSE']._serialized_start=97
  _globals['_PRICERESPONSE']._serialized_end=153
  _globals['_PRICINGSERVICE']._serialized_start=155
  _globals['_PRICINGSERVICE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
