// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ticketDB

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TicketID  int32     `json:"ticket_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type Ticket struct {
	ID        int32          `json:"id"`
	EventName sql.NullString `json:"event_name"`
	Stadium   sql.NullString `json:"stadium"`
	Price     sql.NullInt32  `json:"price"`
	SeatID    sql.NullString `json:"seat_id"`
	Status    sql.NullString `json:"status"`
	EventDate sql.NullTime   `json:"event_date"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
