// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package ticketDB

import (
	"context"
	"database/sql"
)

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, event_name, stadium, price, seat_id, status, event_date
FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id int32) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.EventName,
		&i.Stadium,
		&i.Price,
		&i.SeatID,
		&i.Status,
		&i.EventDate,
	)
	return i, err
}

const getTicketBySeatAndEvent = `-- name: GetTicketBySeatAndEvent :one
SELECT id, event_name, stadium, price, seat_id, status, event_date
FROM tickets
WHERE seat_id = $1 AND event_name = $2
`

type GetTicketBySeatAndEventParams struct {
	SeatID    sql.NullString `json:"seat_id"`
	EventName sql.NullString `json:"event_name"`
}

func (q *Queries) GetTicketBySeatAndEvent(ctx context.Context, arg GetTicketBySeatAndEventParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketBySeatAndEvent, arg.SeatID, arg.EventName)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.EventName,
		&i.Stadium,
		&i.Price,
		&i.SeatID,
		&i.Status,
		&i.EventDate,
	)
	return i, err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :exec
UPDATE tickets
SET status = $1
WHERE id = $2
`

type UpdateTicketStatusParams struct {
	Status sql.NullString `json:"status"`
	ID     int32          `json:"id"`
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketStatus, arg.Status, arg.ID)
	return err
}
