// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ticketDB

import (
	"context"
)

type Querier interface {
	GetTicketByID(ctx context.Context, id int32) (Ticket, error)
	GetTicketBySeatAndEvent(ctx context.Context, arg GetTicketBySeatAndEventParams) (Ticket, error)
}

var _ Querier = (*Queries)(nil)
